@SETLOCAL
@IF NOT DEFINED NODE_PATH (
  @SET "NODE_PATH=E:\learn-ai\webpack5-learn\webpack-customer-demo\node_modules\.pnpm\webpack@5.102.1_webpack-cli@6.0.1\node_modules\webpack\bin\node_modules;E:\learn-ai\webpack5-learn\webpack-customer-demo\node_modules\.pnpm\webpack@5.102.1_webpack-cli@6.0.1\node_modules\webpack\node_modules;E:\learn-ai\webpack5-learn\webpack-customer-demo\node_modules\.pnpm\webpack@5.102.1_webpack-cli@6.0.1\node_modules;E:\learn-ai\webpack5-learn\webpack-customer-demo\node_modules\.pnpm\node_modules"
) ELSE (
  @SET "NODE_PATH=E:\learn-ai\webpack5-learn\webpack-customer-demo\node_modules\.pnpm\webpack@5.102.1_webpack-cli@6.0.1\node_modules\webpack\bin\node_modules;E:\learn-ai\webpack5-learn\webpack-customer-demo\node_modules\.pnpm\webpack@5.102.1_webpack-cli@6.0.1\node_modules\webpack\node_modules;E:\learn-ai\webpack5-learn\webpack-customer-demo\node_modules\.pnpm\webpack@5.102.1_webpack-cli@6.0.1\node_modules;E:\learn-ai\webpack5-learn\webpack-customer-demo\node_modules\.pnpm\node_modules;%NODE_PATH%"
)
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\webpack\bin\webpack.js" %*
) ELSE (
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\webpack\bin\webpack.js" %*
)
